-- Migration 005: Employees Table
CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nik VARCHAR(20) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    ktp_number VARCHAR(16) UNIQUE NOT NULL,
    birth_place VARCHAR(100),
    birth_date DATE,
    gender ENUM('L', 'P') NOT NULL,
    address TEXT,
    phone VARCHAR(20),
    email VARCHAR(100),
    department_id INT NOT NULL,
    position_id INT NOT NULL,
    branch_id INT NOT NULL,
    employment_status ENUM('tetap', 'kontrak', 'probation') NOT NULL DEFAULT 'kontrak',
    join_date DATE NOT NULL,
    contract_end_date DATE NULL,
    photo VARCHAR(255) NULL,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id),
    FOREIGN KEY (position_id) REFERENCES positions(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    INDEX idx_nik (nik),
    INDEX idx_ktp (ktp_number),
    INDEX idx_department (department_id),
    INDEX idx_position (position_id),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
